<a href="https://colab.research.google.com/github/thimeshaA/DeepLearningLabs/blob/main/Lab01_%20Introduction%20to%20Python%20libraries%20for%20Deep%20Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
array = np.random.exponential(scale=1.0, size=(4, 4))
print (array)

[[2.51306297 0.91963025 0.67010506 0.83818394]
 [0.1107429  1.65484967 0.19606774 3.02558169]
 [1.36261446 2.13788384 0.0898741  1.85827269]
 [0.42371958 1.76998347 0.48660452 0.68551053]]
